# Generated by Django 4.0.4 on 2022-05-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareprices',
            name='adjustment',
        ),
    ]
