# Generated by Django 4.0.4 on 2022-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_prices', '0002_sharesplits'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareprices',
            name='value_adjusted',
            field=models.FloatField(null=True),
        ),
    ]
