# Generated by Django 3.1.5 on 2021-02-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ancillary_info", "0002_auto_20210204_2133"),
        ("share_prices", "0002_auto_20210208_2121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareprices",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ancillary_info.companies",
            ),
        ),
    ]
