# Generated by Django 3.1.5 on 2021-02-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_prices", "0003_auto_20210209_2013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shareprices",
            name="adjustment",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shareprices",
            name="value",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="shareprices",
            name="volume",
            field=models.IntegerField(null=True),
        ),
    ]
