# Generated by Django 4.0.4 on 2022-06-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share_prices", "0003_shareprices_value_adjusted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharesplits",
            name="volume",
        ),
    ]
