# Generated by Django 4.0.4 on 2022-05-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('import_type', models.CharField(max_length=255)),
                ('fetchtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Import Record',
                'verbose_name_plural': 'Import Records',
                'db_table': 'import_record',
            },
        ),
    ]
