from django.urls import path

from .views import (
    TransactionListView,
    TransactionDetailView,
    TransactionCreateView,
    transaction_create_view,
    TransactionUpdateView,
    TransactionDeleteView,
    CashListView,
    CashDetailView,
    CashCreateView,
    CashUpdateView,
    CashDeleteView,
    PortfolioOverviewView,
    WishListListView,
    WishListDetailView,
    WishListDeleteView,
    WishListUpdateView,
    wish_list_create,
    wish_list_remove,
    portfolio_overview_charts,
    portfolio_single_chart,
    portfolio_single_chart2,
)

app_name = "portfolio"

urlpatterns = [
    path(
        "transactions/<int:pk>/delete/",
        TransactionDeleteView.as_view(),
        name="transaction_delete",
    ),
    path(
        "transactions/create/",
        TransactionCreateView.as_view(),
        name="transaction_create"
    ),
    # path(
    #     "transactions/create/",
    #     transaction_create_view,
    #     name="transaction_create"
    #     ),
    path(
        "transactions/<int:pk>/",
        TransactionDetailView.as_view(),
        name="transaction_detail",
    ),
    path(
        "transactions/<int:pk>/update/",
        TransactionUpdateView.as_view(),
        name="transaction_update",
    ),
    path(
        "transactions/",
        TransactionListView.as_view(),
        name="transaction_list"),
    path(
        "cash/<int:pk>/delete/",
        CashDeleteView.as_view(),
        name="cash_delete",
    ),
    path(
        "cash/create/",
        CashCreateView.as_view(),
        name="cash_create"
    ),
    path(
        "cash/<int:pk>/",
        CashDetailView.as_view(),
        name="cash_detail",
    ),
    path(
        "cash/<int:pk>/update/",
        CashUpdateView.as_view(),
        name="cash_update",
    ),
    path(
        "cash/",
        CashListView.as_view(),
        name="cash_list"),
    path(
        "overview/",
        PortfolioOverviewView.as_view(),
        name="portfolio_overview"
        ),
    path(
        "overview/charts/",
        portfolio_overview_charts,
        name="portfolio_charts"
        ),
    path(
        "overview/single-chart/",
        portfolio_single_chart,
        name="portfolio_single_chart"
    ),
    path(
        "overview/single-chart2/",
        portfolio_single_chart2,
        name="portfolio_single_chart2",
    ),
    path(
        "wish-list/<int:pk>/delete/",
        WishListDeleteView.as_view(),
        name="wishlist_delete",
    ),
    path(
        "wish-list/",
        WishListListView.as_view(),
        name="wishlist_list"
        ),
    path(
        "wish-list/<int:pk>/",
        WishListDetailView.as_view(),
        name="wishlist_detail"
        ),
    path(
        "wish-list/<int:pk>/update/",
        WishListUpdateView.as_view(),
        name="wishlist_update",
    ),
    path(
        "wish-list/<int:pk>/create/",
        wish_list_create,
        name="wishlist_create"
    ),
    path(
        "wish-list/<int:pk>/remove/",
        wish_list_remove,
        name="wishlist_remove"
    ),
]
