# Generated by Django 4.0.4 on 2022-07-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date_dealt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='investments',
            name='date_settled',
            field=models.DateField(),
        ),
    ]
