# Generated by Django 4.0.4 on 2022-08-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.companies', unique=True),
        ),
    ]
