# Generated by Django 4.0.4 on 2022-09-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_wishlist_decision_investments_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash_holding',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
