# Generated by Django 4.0.4 on 2022-09-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('portfolio', '0006_portfolio_cash_holding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investments',
            new_name='Transactions',
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelTable(
            name='transactions',
            table='transactions',
        ),
    ]
