# Generated by Django 4.0.4 on 2022-09-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('portfolio', '0007_rename_investments_transactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ancillary_info.companies'),
        ),
    ]
