# Generated by Django 4.0.4 on 2022-09-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_cash_total_cash_holding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='total_cash_holding',
            new_name='cash_balance',
        ),
    ]
