# Generated by Django 4.0.4 on 2022-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_total_cash_holding_cash_cash_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_balance',
            field=models.FloatField(null=True),
        ),
    ]
