# Generated by Django 4.0.4 on 2022-09-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('portfolio', '0012_alter_cash_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.companies'),
        ),
    ]
