# Generated by Django 4.0.4 on 2022-09-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_cash_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='num_stock_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
