# Generated by Django 4.0.4 on 2022-09-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_transactions_num_stock_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='fees_paid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='month_end_date',
            field=models.DateField(default="2022-09-09"),
            preserve_default=False,
        ),
    ]
