# Generated by Django 4.0.4 on 2022-09-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_portfolio_fees_paid_portfolio_month_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='current_stock_price',
            new_name='stock_holding',
        ),
    ]
