# Generated by Django 4.0.4 on 2022-09-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_rename_current_stock_price_portfolio_stock_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cash_holding',
        ),
    ]
