# Generated by Django 4.0.4 on 2022-09-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('portfolio', '0020_portfolio_id_delete_positionperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.companies'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
