# Generated by Django 4.0.4 on 2022-09-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('portfolio', '0021_alter_portfolio_company_alter_portfolio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='month_end_date',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ancillary_info.companies'),
        ),
    ]
