# Generated by Django 4.0.4 on 2022-09-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_portfolio_id_remove_portfolio_month_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='num_shares',
            new_name='num_shares_held',
        ),
    ]
