# Generated by Django 4.0.4 on 2022-09-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_rename_num_shares_portfolio_num_shares_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cash_holding',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='fees_paid',
        ),
    ]
