# Generated by Django 4.0.4 on 2022-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_remove_portfolio_cash_holding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pct_holding',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
