# Generated by Django 4.0.4 on 2022-09-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_rename_num_shares_held_portfolio_latest_shares_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='stock_holding',
            new_name='latest_shares_holding',
        ),
    ]
