# Generated by Django 4.0.4 on 2022-09-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_rename_stock_holding_portfolio_latest_shares_holding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='pct_holding',
            new_name='company_pct_holding',
        ),
    ]
