# Generated by Django 4.0.4 on 2022-10-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_wishlist_latest_financial_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='dcf_intrinsic_value',
            field=models.FloatField(default=999),
            preserve_default=False,
        ),
    ]
