"""
Django settings for value_investing project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
from configurations import Configuration, values

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_NAME = "value_investing"
_lower_django_configuration = os.environ["DJANGO_CONFIGURATION"].lower()
PROJECT_ENVIRONMENT_SLUG = f"{PROJECT_NAME}_{_lower_django_configuration}"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
class Common(Configuration):
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.Value(PROJECT_NAME, environ_name="SECRET_KEY")

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "value_investing.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "value_investing.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/3.1/ref/settings/#databases

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

    # Password validation
    # https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": ("django.contrib.auth.password_validation"
                     ".UserAttributeSimilarityValidator"),
        },
        {
            "NAME": ("django.contrib.auth.password_validation"
                     ".MinimumLengthValidator"),
        },
        {
            "NAME": ("django.contrib.auth.password_validation"
                     ".CommonPasswordValidator"),
        },
        {
            "NAME": ("django.contrib.auth.password_validation"
                     ".NumericPasswordValidator"),
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/3.1/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.1/howto/static-files/

    STATIC_URL = "/static/"


class Dev(Common):
    """
    The in-development settings and the default configuration.
    """

    DEBUG = True
    ALLOWED_HOSTS = ["*"]


class Deployed(Common):
    """
    The deployed settings and the default configuration.
    """

    DEBUG = False
    SENTRY_ENABLED = False


class Prod(Deployed):
    """
    The production settings and the default configuration.
    """

    # TODO change to whatever domain production deployment
    ALLOWED_HOSTS = ["*"]
    SENTRY_ENABLED = True
