# Generated by Django 4.0.4 on 2022-06-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidm', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('company_summary', models.TextField()),
                ('share_listing', models.CharField(max_length=255, null=True)),
                ('company_type', models.CharField(max_length=255, null=True)),
                ('industry_name', models.CharField(max_length=255, null=True)),
                ('revenue', models.FloatField()),
                ('earnings', models.FloatField()),
                ('dividends', models.FloatField()),
                ('capital_expenditure', models.FloatField()),
                ('net_income', models.FloatField()),
                ('total_equity', models.FloatField()),
                ('share_price', models.FloatField()),
                ('debt_to_equity', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('return_on_equity', models.FloatField()),
                ('equity_per_share', models.FloatField()),
                ('price_to_earnings', models.FloatField()),
                ('price_to_equity', models.FloatField()),
                ('earnings_yield_return', models.FloatField()),
                ('fcf', models.FloatField()),
                ('dividend_payment', models.CharField(max_length=10, null=True)),
                ('dividend_cover', models.FloatField()),
                ('capital_employed', models.FloatField()),
                ('roce', models.FloatField()),
                ('dcf_intrinsic_value', models.FloatField()),
                ('margin_safety', models.FloatField()),
                ('estimated_growth_rate', models.FloatField()),
                ('estimated_discount_rate', models.FloatField()),
                ('estimated_long_term_growth_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Dashboard Companies',
                'db_table': 'dashboard_company',
            },
        ),
    ]
