# Generated by Django 4.0.4 on 2022-09-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCompany',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ancillary_info.companies')),
                ('tidm', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('company_summary', models.TextField()),
                ('share_listing', models.CharField(max_length=255, null=True)),
                ('company_type', models.CharField(max_length=255, null=True)),
                ('industry_name', models.CharField(max_length=255, null=True)),
                ('revenue', models.FloatField(null=True)),
                ('earnings', models.FloatField(null=True)),
                ('dividends', models.FloatField(null=True)),
                ('capital_expenditure', models.FloatField(null=True)),
                ('net_income', models.FloatField(null=True)),
                ('total_equity', models.FloatField(null=True)),
                ('share_price', models.FloatField(null=True)),
                ('debt_to_equity', models.FloatField(null=True)),
                ('current_ratio', models.FloatField(null=True)),
                ('return_on_equity', models.FloatField(null=True)),
                ('equity_per_share', models.FloatField(null=True)),
                ('price_to_earnings', models.FloatField(null=True)),
                ('price_to_equity', models.FloatField(null=True)),
                ('earnings_yield', models.FloatField(null=True)),
                ('annual_yield_return', models.FloatField(null=True)),
                ('fcf', models.FloatField(null=True)),
                ('dividend_cover', models.FloatField(null=True)),
                ('capital_employed', models.FloatField(null=True)),
                ('roce', models.FloatField(null=True)),
                ('dcf_intrinsic_value', models.FloatField(null=True)),
                ('margin_safety', models.FloatField(null=True)),
                ('latest_margin_of_safety', models.FloatField(null=True)),
                ('estimated_growth_rate', models.FloatField(null=True)),
                ('estimated_discount_rate', models.FloatField(null=True)),
                ('estimated_long_term_growth_rate', models.FloatField(null=True)),
                ('pick_source', models.CharField(max_length=255)),
                ('exchange_country', models.CharField(max_length=255)),
                ('currency_symbol', models.CharField(max_length=5)),
                ('latest_financial_date', models.DateTimeField(null=True)),
                ('latest_share_price_date', models.DateTimeField(null=True)),
                ('latest_share_price', models.FloatField(null=True)),
                ('market_cap', models.FloatField(null=True)),
                ('decision_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.decisiontype')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Companies',
                'db_table': 'dashboard_company',
            },
        ),
    ]
