# Generated by Django 6.0.3 on 2026-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcompany',
            name='dividend_payout_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashboardcompany',
            name='gross_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashboardcompany',
            name='interest_coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashboardcompany',
            name='net_margin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dashboardcompany',
            name='operating_margin',
            field=models.FloatField(null=True),
        ),
    ]
