# Generated by Django 4.0.4 on 2022-06-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0002_remove_dashboardcompany_acquisitions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardcompany',
            old_name='turnover',
            new_name='revenue',
        ),
    ]
