# Generated by Django 4.0.4 on 2022-06-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0002_rename_earnings_yield_return_dashboardcompany_annual_yield_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcompany',
            name='dividend_payment',
        ),
    ]
