# Generated by Django 4.0.4 on 2022-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0002_dashboardcompany_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcompany',
            name='latest_margin_of_safety',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
