# Generated by Django 3.1.5 on 2021-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_company", "0002_auto_20210408_2056"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardcompany",
            name="net_profit",
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
    ]
