# Generated by Django 4.0.4 on 2022-06-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0003_rename_turnover_dashboardcompany_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardcompany',
            old_name='net_profit',
            new_name='net_income',
        ),
        migrations.RemoveField(
            model_name='dashboardcompany',
            name='total_borrowing',
        ),
    ]
