# Generated by Django 4.0.4 on 2022-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0003_dashboardcompany_latest_share_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcompany',
            name='decision_type',
            field=models.IntegerField(default=1),
        ),
    ]
