# Generated by Django 3.1.5 on 2021-04-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0003_dashboardcompany_net_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcompany',
            name='total_equity',
            field=models.FloatField(default=-9999),
            preserve_default=False,
        ),
    ]
