# Generated by Django 4.0.4 on 2022-06-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0004_rename_net_profit_dashboardcompany_net_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcompany',
            name='shareholder_equity',
        ),
    ]
