# Generated by Django 4.0.4 on 2022-09-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0006_remove_companies_wish_list'),
        ('dashboard_company', '0005_alter_dashboardcompany_decision_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcompany',
            name='decision_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.decisiontype'),
        ),
    ]
