# Generated by Django 4.0.4 on 2022-06-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0005_remove_dashboardcompany_shareholder_equity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardcompany',
            old_name='annual_return',
            new_name='earnings_yield_return',
        ),
    ]
