# Generated by Django 4.0.4 on 2022-06-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0006_rename_annual_return_dashboardcompany_earnings_yield_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardcompany',
            old_name='fcf_ps',
            new_name='fcf',
        ),
    ]
