# Generated by Django 4.0.4 on 2022-06-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_company', '0007_rename_fcf_ps_dashboardcompany_fcf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcompany',
            name='debt_ratio',
        ),
    ]
