# Generated by Django 4.0.4 on 2022-05-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Company Types',
                'db_table': 'company_type',
            },
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_listing', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Exchanges',
                'db_table': 'exchanges',
            },
        ),
        migrations.CreateModel(
            name='IndustryRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Industry Risks',
                'db_table': 'industry_risk',
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Report Types',
                'db_table': 'report_type',
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_section', models.CharField(max_length=255)),
                ('report_section_last', models.CharField(max_length=255)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.reporttype')),
            ],
            options={
                'verbose_name_plural': 'Report Sections',
                'db_table': 'report_section',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=255)),
                ('limit_logic', models.CharField(max_length=255)),
                ('limit_value', models.CharField(max_length=255)),
                ('param_description', models.CharField(max_length=255)),
                ('report_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.reportsection')),
            ],
            options={
                'verbose_name_plural': 'Parameters',
                'db_table': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255)),
                ('industry_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.industryrisk')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidm', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('company_summary', models.TextField()),
                ('comp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.companytype')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.exchanges')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.industries')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CalcVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ancillary_info.parameters')),
            ],
            options={
                'verbose_name_plural': 'Calculation Variables',
                'db_table': 'calc_variables',
            },
        ),
    ]
