# Generated by Django 4.0.4 on 2022-05-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanges',
            old_name='share_listing',
            new_name='value',
        ),
    ]
