# Generated by Django 4.0.4 on 2022-06-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='param_description',
            field=models.TextField(),
        ),
    ]
