# Generated by Django 4.0.4 on 2022-05-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0002_rename_share_listing_exchanges_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytype',
            old_name='company_type',
            new_name='value',
        ),
    ]
