# Generated by Django 4.0.4 on 2022-05-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0002_datasource_paramsapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramsapi',
            old_name='datasource_id',
            new_name='datasource',
        ),
        migrations.RenameField(
            model_name='paramsapi',
            old_name='param_id',
            new_name='param',
        ),
    ]
