# Generated by Django 4.0.4 on 2022-08-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ancillary_info", "0003_remove_dcfvariables_parameter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currencies",
            old_name="value",
            new_name="symbol",
        ),
    ]
