# Generated by Django 4.0.4 on 2022-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0003_paramsapi_created_at_paramsapi_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Decision Types',
                'db_table': 'decision_type',
            },
        ),
    ]
