# Generated by Django 4.0.4 on 2022-05-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0003_rename_company_type_companytype_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustryRisk',
            new_name='Sectors',
        ),
        migrations.AlterModelOptions(
            name='sectors',
            options={'verbose_name_plural': 'Sectors'},
        ),
        migrations.RenameField(
            model_name='industries',
            old_name='industry_name',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='sectors',
            old_name='industry_type',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='industry_risk',
        ),
        migrations.AlterModelTable(
            name='sectors',
            table='sectors',
        ),
    ]
