# Generated by Django 4.0.4 on 2022-07-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0004_decisiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='wish_list',
            field=models.BooleanField(default=False),
        ),
    ]
