# Generated by Django 4.0.4 on 2022-08-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0004_rename_value_currencies_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
