# Generated by Django 4.0.4 on 2022-05-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0004_rename_industryrisk_sectors_alter_sectors_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='report_name',
            new_name='value',
        ),
    ]
