# Generated by Django 4.0.4 on 2022-08-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0005_currencies_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='wish_list',
        ),
    ]
