# Generated by Django 4.0.4 on 2022-05-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0005_rename_report_name_reporttype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='report_section',
        ),
        migrations.DeleteModel(
            name='ReportSection',
        ),
    ]
