# Generated by Django 4.0.4 on 2022-05-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ancillary_info", "0005_alter_companies_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="datasource",
            table="datasources",
        ),
    ]
