# Generated by Django 4.0.4 on 2022-05-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancillary_info', '0007_countries_currencies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalcVariables',
        ),
    ]
