# Generated by Django 4.0.4 on 2022-05-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_reports', '0001_initial'),
        ('calculated_stats', '0001_initial'),
        ('ranking_stats', '0001_initial'),
        ('ancillary_info', '0008_delete_calcvariables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Params',
        ),
        migrations.AlterModelTable(
            name='params',
            table='params',
        ),
    ]
