# Generated by Django 3.1.5 on 2021-02-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculated_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedstats',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
